

export interface SP500Stock {
  ticker: string;
  name: string;
  sector: string;
}

export const SP500_CONSTITUENTS: SP500Stock[] = [
  
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology" },
  { ticker: "MSFT", name: "Microsoft Corporation", sector: "Technology" },
  { ticker: "NVDA", name: "NVIDIA Corporation", sector: "Technology" },
  { ticker: "AVGO", name: "Broadcom Inc.", sector: "Technology" },
  { ticker: "ORCL", name: "Oracle Corporation", sector: "Technology" },
  { ticker: "CRM", name: "Salesforce Inc.", sector: "Technology" },
  { ticker: "ADBE", name: "Adobe Inc.", sector: "Technology" },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Technology" },
  { ticker: "CSCO", name: "Cisco Systems Inc.", sector: "Technology" },
  { ticker: "ACN", name: "Accenture plc", sector: "Technology" },
  { ticker: "IBM", name: "IBM Corporation", sector: "Technology" },
  { ticker: "INTC", name: "Intel Corporation", sector: "Technology" },
  { ticker: "INTU", name: "Intuit Inc.", sector: "Technology" },
  { ticker: "QCOM", name: "Qualcomm Inc.", sector: "Technology" },
  { ticker: "TXN", name: "Texas Instruments", sector: "Technology" },
  { ticker: "NOW", name: "ServiceNow Inc.", sector: "Technology" },
  { ticker: "AMAT", name: "Applied Materials", sector: "Technology" },
  { ticker: "ADI", name: "Analog Devices", sector: "Technology" },
  { ticker: "LRCX", name: "Lam Research", sector: "Technology" },
  { ticker: "MU", name: "Micron Technology", sector: "Technology" },
  { ticker: "KLAC", name: "KLA Corporation", sector: "Technology" },
  { ticker: "SNPS", name: "Synopsys Inc.", sector: "Technology" },
  { ticker: "CDNS", name: "Cadence Design Systems", sector: "Technology" },
  { ticker: "MCHP", name: "Microchip Technology", sector: "Technology" },
  { ticker: "MSI", name: "Motorola Solutions", sector: "Technology" },
  
  
  { ticker: "JPM", name: "JPMorgan Chase", sector: "Financials" },
  { ticker: "V", name: "Visa Inc.", sector: "Financials" },
  { ticker: "MA", name: "Mastercard Inc.", sector: "Financials" },
  { ticker: "BAC", name: "Bank of America", sector: "Financials" },
  { ticker: "WFC", name: "Wells Fargo", sector: "Financials" },
  { ticker: "GS", name: "Goldman Sachs", sector: "Financials" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Financials" },
  { ticker: "AXP", name: "American Express", sector: "Financials" },
  { ticker: "BLK", name: "BlackRock Inc.", sector: "Financials" },
  { ticker: "C", name: "Citigroup Inc.", sector: "Financials" },
  { ticker: "SCHW", name: "Charles Schwab", sector: "Financials" },
  { ticker: "CB", name: "Chubb Limited", sector: "Financials" },
  { ticker: "SPGI", name: "S&P Global", sector: "Financials" },
  { ticker: "MMC", name: "Marsh & McLennan", sector: "Financials" },
  { ticker: "PGR", name: "Progressive Corp", sector: "Financials" },
  { ticker: "AON", name: "Aon plc", sector: "Financials" },
  { ticker: "ICE", name: "Intercontinental Exchange", sector: "Financials" },
  { ticker: "CME", name: "CME Group", sector: "Financials" },
  { ticker: "MCO", name: "Moody's Corporation", sector: "Financials" },
  { ticker: "USB", name: "U.S. Bancorp", sector: "Financials" },
  { ticker: "PNC", name: "PNC Financial Services", sector: "Financials" },
  { ticker: "TFC", name: "Truist Financial", sector: "Financials" },
  { ticker: "AIG", name: "American International Group", sector: "Financials" },
  { ticker: "MET", name: "MetLife Inc.", sector: "Financials" },
  { ticker: "PRU", name: "Prudential Financial", sector: "Financials" },
  
  
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Healthcare" },
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { ticker: "LLY", name: "Eli Lilly", sector: "Healthcare" },
  { ticker: "MRK", name: "Merck & Co.", sector: "Healthcare" },
  { ticker: "ABBV", name: "AbbVie Inc.", sector: "Healthcare" },
  { ticker: "PFE", name: "Pfizer Inc.", sector: "Healthcare" },
  { ticker: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare" },
  { ticker: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
  { ticker: "DHR", name: "Danaher Corporation", sector: "Healthcare" },
  { ticker: "AMGN", name: "Amgen Inc.", sector: "Healthcare" },
  { ticker: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare" },
  { ticker: "CVS", name: "CVS Health", sector: "Healthcare" },
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Healthcare" },
  { ticker: "MDT", name: "Medtronic plc", sector: "Healthcare" },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Healthcare" },
  { ticker: "ELV", name: "Elevance Health", sector: "Healthcare" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare" },
  { ticker: "SYK", name: "Stryker Corporation", sector: "Healthcare" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare" },
  { ticker: "CI", name: "Cigna Group", sector: "Healthcare" },
  { ticker: "ZTS", name: "Zoetis Inc.", sector: "Healthcare" },
  { ticker: "BSX", name: "Boston Scientific", sector: "Healthcare" },
  { ticker: "HCA", name: "HCA Healthcare", sector: "Healthcare" },
  { ticker: "MCK", name: "McKesson Corporation", sector: "Healthcare" },
  
  
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary" },
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary" },
  { ticker: "HD", name: "Home Depot", sector: "Consumer Discretionary" },
  { ticker: "MCD", name: "McDonald's Corp", sector: "Consumer Discretionary" },
  { ticker: "NKE", name: "Nike Inc.", sector: "Consumer Discretionary" },
  { ticker: "LOW", name: "Lowe's Companies", sector: "Consumer Discretionary" },
  { ticker: "SBUX", name: "Starbucks Corp", sector: "Consumer Discretionary" },
  { ticker: "TJX", name: "TJX Companies", sector: "Consumer Discretionary" },
  { ticker: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary" },
  { ticker: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer Discretionary" },
  { ticker: "ORLY", name: "O'Reilly Automotive", sector: "Consumer Discretionary" },
  { ticker: "AZO", name: "AutoZone Inc.", sector: "Consumer Discretionary" },
  { ticker: "MAR", name: "Marriott International", sector: "Consumer Discretionary" },
  { ticker: "HLT", name: "Hilton Worldwide", sector: "Consumer Discretionary" },
  { ticker: "ROST", name: "Ross Stores", sector: "Consumer Discretionary" },
  { ticker: "DHI", name: "D.R. Horton", sector: "Consumer Discretionary" },
  { ticker: "LEN", name: "Lennar Corporation", sector: "Consumer Discretionary" },
  { ticker: "YUM", name: "Yum! Brands", sector: "Consumer Discretionary" },
  { ticker: "EBAY", name: "eBay Inc.", sector: "Consumer Discretionary" },
  { ticker: "GM", name: "General Motors", sector: "Consumer Discretionary" },
  { ticker: "F", name: "Ford Motor", sector: "Consumer Discretionary" },
  { ticker: "TGT", name: "Target Corporation", sector: "Consumer Discretionary" },
  { ticker: "DG", name: "Dollar General", sector: "Consumer Discretionary" },
  { ticker: "DLTR", name: "Dollar Tree", sector: "Consumer Discretionary" },
  
  
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer Staples" },
  { ticker: "KO", name: "Coca-Cola Company", sector: "Consumer Staples" },
  { ticker: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples" },
  { ticker: "COST", name: "Costco Wholesale", sector: "Consumer Staples" },
  { ticker: "WMT", name: "Walmart Inc.", sector: "Consumer Staples" },
  { ticker: "PM", name: "Philip Morris International", sector: "Consumer Staples" },
  { ticker: "MO", name: "Altria Group", sector: "Consumer Staples" },
  { ticker: "MDLZ", name: "Mondelez International", sector: "Consumer Staples" },
  { ticker: "CL", name: "Colgate-Palmolive", sector: "Consumer Staples" },
  { ticker: "KMB", name: "Kimberly-Clark", sector: "Consumer Staples" },
  { ticker: "GIS", name: "General Mills", sector: "Consumer Staples" },
  { ticker: "STZ", name: "Constellation Brands", sector: "Consumer Staples" },
  { ticker: "KHC", name: "Kraft Heinz", sector: "Consumer Staples" },
  { ticker: "SYY", name: "Sysco Corporation", sector: "Consumer Staples" },
  { ticker: "HSY", name: "Hershey Company", sector: "Consumer Staples" },
  { ticker: "K", name: "Kellanova", sector: "Consumer Staples" },
  { ticker: "EL", name: "Estée Lauder", sector: "Consumer Staples" },
  { ticker: "KR", name: "Kroger Company", sector: "Consumer Staples" },
  { ticker: "CHD", name: "Church & Dwight", sector: "Consumer Staples" },
  { ticker: "CAG", name: "Conagra Brands", sector: "Consumer Staples" },
  
  
  { ticker: "XOM", name: "Exxon Mobil", sector: "Energy" },
  { ticker: "CVX", name: "Chevron Corporation", sector: "Energy" },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy" },
  { ticker: "EOG", name: "EOG Resources", sector: "Energy" },
  { ticker: "SLB", name: "Schlumberger", sector: "Energy" },
  { ticker: "MPC", name: "Marathon Petroleum", sector: "Energy" },
  { ticker: "PSX", name: "Phillips 66", sector: "Energy" },
  { ticker: "VLO", name: "Valero Energy", sector: "Energy" },
  { ticker: "PXD", name: "Pioneer Natural Resources", sector: "Energy" },
  { ticker: "OXY", name: "Occidental Petroleum", sector: "Energy" },
  { ticker: "WMB", name: "Williams Companies", sector: "Energy" },
  { ticker: "KMI", name: "Kinder Morgan", sector: "Energy" },
  { ticker: "HES", name: "Hess Corporation", sector: "Energy" },
  { ticker: "HAL", name: "Halliburton", sector: "Energy" },
  { ticker: "DVN", name: "Devon Energy", sector: "Energy" },
  { ticker: "BKR", name: "Baker Hughes", sector: "Energy" },
  { ticker: "FANG", name: "Diamondback Energy", sector: "Energy" },
  { ticker: "OKE", name: "ONEOK Inc.", sector: "Energy" },
  { ticker: "TRGP", name: "Targa Resources", sector: "Energy" },
  { ticker: "MRO", name: "Marathon Oil", sector: "Energy" },
  
  
  { ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrials" },
  { ticker: "DE", name: "Deere & Company", sector: "Industrials" },
  { ticker: "GE", name: "GE Aerospace", sector: "Industrials" },
  { ticker: "UNP", name: "Union Pacific", sector: "Industrials" },
  { ticker: "RTX", name: "RTX Corporation", sector: "Industrials" },
  { ticker: "HON", name: "Honeywell International", sector: "Industrials" },
  { ticker: "BA", name: "Boeing Company", sector: "Industrials" },
  { ticker: "LMT", name: "Lockheed Martin", sector: "Industrials" },
  { ticker: "UPS", name: "United Parcel Service", sector: "Industrials" },
  { ticker: "ADP", name: "Automatic Data Processing", sector: "Industrials" },
  { ticker: "ETN", name: "Eaton Corporation", sector: "Industrials" },
  { ticker: "NOC", name: "Northrop Grumman", sector: "Industrials" },
  { ticker: "GD", name: "General Dynamics", sector: "Industrials" },
  { ticker: "WM", name: "Waste Management", sector: "Industrials" },
  { ticker: "CSX", name: "CSX Corporation", sector: "Industrials" },
  { ticker: "NSC", name: "Norfolk Southern", sector: "Industrials" },
  { ticker: "FDX", name: "FedEx Corporation", sector: "Industrials" },
  { ticker: "ITW", name: "Illinois Tool Works", sector: "Industrials" },
  { ticker: "EMR", name: "Emerson Electric", sector: "Industrials" },
  { ticker: "PH", name: "Parker-Hannifin", sector: "Industrials" },
  { ticker: "JCI", name: "Johnson Controls", sector: "Industrials" },
  { ticker: "TT", name: "Trane Technologies", sector: "Industrials" },
  { ticker: "PCAR", name: "PACCAR Inc.", sector: "Industrials" },
  { ticker: "CARR", name: "Carrier Global", sector: "Industrials" },
  { ticker: "CMI", name: "Cummins Inc.", sector: "Industrials" },
  
  
  { ticker: "META", name: "Meta Platforms", sector: "Communication Services" },
  { ticker: "GOOGL", name: "Alphabet Inc. Class A", sector: "Communication Services" },
  { ticker: "GOOG", name: "Alphabet Inc. Class C", sector: "Communication Services" },
  { ticker: "NFLX", name: "Netflix Inc.", sector: "Communication Services" },
  { ticker: "DIS", name: "Walt Disney Company", sector: "Communication Services" },
  { ticker: "VZ", name: "Verizon Communications", sector: "Communication Services" },
  { ticker: "T", name: "AT&T Inc.", sector: "Communication Services" },
  { ticker: "CMCSA", name: "Comcast Corporation", sector: "Communication Services" },
  { ticker: "TMUS", name: "T-Mobile US", sector: "Communication Services" },
  { ticker: "CHTR", name: "Charter Communications", sector: "Communication Services" },
  { ticker: "WBD", name: "Warner Bros. Discovery", sector: "Communication Services" },
  { ticker: "EA", name: "Electronic Arts", sector: "Communication Services" },
  { ticker: "TTWO", name: "Take-Two Interactive", sector: "Communication Services" },
  { ticker: "MTCH", name: "Match Group", sector: "Communication Services" },
  { ticker: "OMC", name: "Omnicom Group", sector: "Communication Services" },
  { ticker: "IPG", name: "Interpublic Group", sector: "Communication Services" },
  { ticker: "PARA", name: "Paramount Global", sector: "Communication Services" },
  { ticker: "LYV", name: "Live Nation Entertainment", sector: "Communication Services" },
  { ticker: "FOXA", name: "Fox Corporation Class A", sector: "Communication Services" },
  { ticker: "NWS", name: "News Corp Class B", sector: "Communication Services" },
  
  
  { ticker: "NEE", name: "NextEra Energy", sector: "Utilities" },
  { ticker: "DUK", name: "Duke Energy", sector: "Utilities" },
  { ticker: "SO", name: "Southern Company", sector: "Utilities" },
  { ticker: "D", name: "Dominion Energy", sector: "Utilities" },
  { ticker: "SRE", name: "Sempra", sector: "Utilities" },
  { ticker: "AEP", name: "American Electric Power", sector: "Utilities" },
  { ticker: "EXC", name: "Exelon Corporation", sector: "Utilities" },
  { ticker: "XEL", name: "Xcel Energy", sector: "Utilities" },
  { ticker: "PCG", name: "PG&E Corporation", sector: "Utilities" },
  { ticker: "ED", name: "Consolidated Edison", sector: "Utilities" },
  { ticker: "WEC", name: "WEC Energy Group", sector: "Utilities" },
  { ticker: "EIX", name: "Edison International", sector: "Utilities" },
  { ticker: "ES", name: "Eversource Energy", sector: "Utilities" },
  { ticker: "AWK", name: "American Water Works", sector: "Utilities" },
  { ticker: "DTE", name: "DTE Energy", sector: "Utilities" },
  { ticker: "ETR", name: "Entergy Corporation", sector: "Utilities" },
  { ticker: "PPL", name: "PPL Corporation", sector: "Utilities" },
  { ticker: "FE", name: "FirstEnergy Corp", sector: "Utilities" },
  { ticker: "AEE", name: "Ameren Corporation", sector: "Utilities" },
  { ticker: "CMS", name: "CMS Energy", sector: "Utilities" },
  
  
  { ticker: "LIN", name: "Linde plc", sector: "Materials" },
  { ticker: "APD", name: "Air Products", sector: "Materials" },
  { ticker: "SHW", name: "Sherwin-Williams", sector: "Materials" },
  { ticker: "ECL", name: "Ecolab Inc.", sector: "Materials" },
  { ticker: "FCX", name: "Freeport-McMoRan", sector: "Materials" },
  { ticker: "NEM", name: "Newmont Corporation", sector: "Materials" },
  { ticker: "NUE", name: "Nucor Corporation", sector: "Materials" },
  { ticker: "DOW", name: "Dow Inc.", sector: "Materials" },
  { ticker: "DD", name: "DuPont de Nemours", sector: "Materials" },
  { ticker: "PPG", name: "PPG Industries", sector: "Materials" },
  { ticker: "VMC", name: "Vulcan Materials", sector: "Materials" },
  { ticker: "MLM", name: "Martin Marietta Materials", sector: "Materials" },
  { ticker: "CTVA", name: "Corteva Inc.", sector: "Materials" },
  { ticker: "IFF", name: "International Flavors & Fragrances", sector: "Materials" },
  { ticker: "CF", name: "CF Industries", sector: "Materials" },
  { ticker: "ALB", name: "Albemarle Corporation", sector: "Materials" },
  { ticker: "STLD", name: "Steel Dynamics", sector: "Materials" },
  { ticker: "PKG", name: "Packaging Corp of America", sector: "Materials" },
  { ticker: "IP", name: "International Paper", sector: "Materials" },
  { ticker: "EMN", name: "Eastman Chemical", sector: "Materials" },
  
  
  { ticker: "PLD", name: "Prologis Inc.", sector: "Real Estate" },
  { ticker: "AMT", name: "American Tower", sector: "Real Estate" },
  { ticker: "EQIX", name: "Equinix Inc.", sector: "Real Estate" },
  { ticker: "CCI", name: "Crown Castle", sector: "Real Estate" },
  { ticker: "PSA", name: "Public Storage", sector: "Real Estate" },
  { ticker: "O", name: "Realty Income", sector: "Real Estate" },
  { ticker: "SPG", name: "Simon Property Group", sector: "Real Estate" },
  { ticker: "WELL", name: "Welltower Inc.", sector: "Real Estate" },
  { ticker: "DLR", name: "Digital Realty Trust", sector: "Real Estate" },
  { ticker: "AVB", name: "AvalonBay Communities", sector: "Real Estate" },
  { ticker: "EQR", name: "Equity Residential", sector: "Real Estate" },
  { ticker: "VICI", name: "VICI Properties", sector: "Real Estate" },
  { ticker: "WY", name: "Weyerhaeuser", sector: "Real Estate" },
  { ticker: "VTR", name: "Ventas Inc.", sector: "Real Estate" },
  { ticker: "ARE", name: "Alexandria Real Estate", sector: "Real Estate" },
  { ticker: "EXR", name: "Extra Space Storage", sector: "Real Estate" },
  { ticker: "IRM", name: "Iron Mountain", sector: "Real Estate" },
  { ticker: "MAA", name: "Mid-America Apartment", sector: "Real Estate" },
  { ticker: "ESS", name: "Essex Property Trust", sector: "Real Estate" },
  { ticker: "SBAC", name: "SBA Communications", sector: "Real Estate" },
];

export const SP500_TICKERS = new Set(SP500_CONSTITUENTS.map((s) => s.ticker));

export const TICKER_SECTOR_MAP = new Map(
  SP500_CONSTITUENTS.map((s) => [s.ticker, s.sector])
);

export const SECTORS = [
  "Technology",
  "Financials",
  "Healthcare",
  "Consumer Discretionary",
  "Consumer Staples",
  "Energy",
  "Industrials",
  "Communication Services",
  "Utilities",
  "Materials",
  "Real Estate",
] as const;

export const ALLOWED_INDICES = new Set([
  "^GSPC",  
  "^SPX",   
  "^NDX",   
  "^IXIC",  
  "^DJI",   
  "^RUT",   
  "^VIX",   
]);

export const DEFAULT_PARAMS = {
  lookbackWindow: 35,
  zScoreWindow: 10,
  timePeriod: 180,
  minCorrelation: 0.85,
  minRSquared: 0.72,
  topPairsCount: 20,
} as const;

export const STAT_THRESHOLDS = {
  tradableMinCorrelation: 0.85,
  tradableMinRSquared: 0.72,
  unstableMinCorrelation: 0.75,
  unstableMaxRSquared: 0.72,
  stableMinConsistency: 0.80,
  mediumMinConsistency: 0.60,
} as const;
